server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://34.41.170.207:32003/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false